    # 1. Palindrome of a string. Ex. madam, liril, anna

# def foo(str1):
#     n=len(str1)
#     for i in range(n):
#         if str1[i]==str1[n-1-i]:
#             return True
#         else:
#             return False 

# print(foo("madam"))
# print(foo("anna"))
# print(foo("pratik"))



# def prime_no(num):
#     if num==1:
#         print("not a prime number")
#     else:
#         for i in range(2,num//2+1):
#             if num%i==0:
#                 break
#         else:
#             print(num)

# for i in range(2,50):
#     prime_no(i)


# def fibo(num):
#     if num==0:
#         return 0
#     elif num==1:
#         return 1
#     else:
#         return fibo(num-1)+fibo(num-2)

# for i in range(0,10):
#     print(fibo(i))


































